### ISSUE TITLE
Alias seems to be not required

### ISSUE THREAD

**Issue by nohillside** [konrad-amtenbrink/mkc#1]
The Homebrew formula installs a link to the binary in `$(brew --prefix)/bin` automatically (which should be in `PATH` already), so the alias seems unnecessary.

As written, it's even dangerous because `$(brew --prefix)` is different on Intel and on ARM, and the location in Cellar changes each time you bump the version number.

**Comment by konrad-amtenbrink** [comment]
Yup you are right - will remove that from the readme - thanks :)
